In [2]:
import numpy as np
import pandas as pd

df = df = pd.read_csv('./chocolate_preprocessed.csv')

In [3]:
a=(100/df['Rating'].max())
df['Rating'] = df['Rating']*a

df.head()

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru

In [4]:
df['price(100g)'] = (df['Rating']*df['Cocoa Percent'])*25
df

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,A. Morin,Agua Grande,2016,63.0,France,75.0,Blend,Sao Tome,118125.0
1,A. Morin,Kpime,2015,70.0,France,55.0,Blend,Togo,96250.0
2,A. Morin,Atsane,2015,70.0,France,60.0,Blend,Togo,105000.0
3,A. Morin,Akata,2015,70.0,France,70.0,Blend,Togo,122500.0
4,A. Morin,Quilla,2015,70.0,France,70.0,Blend,Peru,122500.0
...,...,...,...,...,...,...,...,...,...
1790,Zotter,Peru,2011,70.0,Austria,75.0,Blend,Peru,131250.0
1791,Zotter,Congo,2011,65.0,Austria,60.0,Forastero,Congo,97500.0
1792,Zotter,Kerala State,2011,65.0,Austria,70.0,Forastero,India,113750.0
1793,Zotter,Kerala State,2011,62.0,Austria,65.0,Blend,India,100750.0
1794,Zotter,"Brazil, Mitzi Blue",2010,65.0,Austria,60.0,Blend,Brazil,97500.0

In [24]:
m=pd.DataFrame(df[df['Cocoa Percent']>70.0])
dark_chocolates = m.reset_index()
dark_chocolates.drop(['index'],axis=1,inplace=True)

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
26,Adi,"Vanua Levu, Toto-A",2011,80.0,Fiji,65.0,Trinitario,Fiji,130000.0
27,Adi,Vanua Levu,2011,88.0,Fiji,70.0,Trinitario,Fiji,154000.0
28,Adi,"Vanua Levu, Ami-Ami-CA",2011,72.0,Fiji,70.0,Trinitario,Fiji,126000.0
32,Akesson's (Pralus),"Bali (west), Sukrama Family, Melaya area",2011,75.0,Switzerland,75.0,Trinitario,Indonesia,140625.0
33,Akesson's (Pralus),"Madagascar, Ambolikapiky P.",2010,75.0,Switzerland,55.0,Criollo,Madagascar,103125.0
...,...,...,...,...,...,...,...,...,...
1778,Zotter,Raw,2014,80.0,Austria,55.0,Blend,Other,110000.0
1779,Zotter,"Bocas del Toro, Cocabo Co-op",2012,72.0,Austria,70.0,Blend,Panama,126000.0
1784,Zotter,El Oro,2012,75.0,Austria,60.0,Forastero (Nacional),Ecuador,112500.0
1785,Zotter,Huiwani Coop,2012,75.0,Austria,60.0,"Criollo, Trinitario",Papua New Guinea,112500.0
1786,Zotter,El Ceibo Coop,2012,90.0,Austria,65.0,Blend,Bolivia,146250.0

In [13]:
has_Trinitario = np.array(dark_chocolates['Bean Type']=='Trinitario')

In [23]:
dark_chocolates.loc[has_Trinitario, 'price(100g)']=dark_chocolates.loc[has_Trinitario, 'price(100g)']*1.1
dark_chocolates

,Company,Specific Bean Origin,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin,price(100g)
0,Adi,"Vanua Levu, Toto-A",2011,80.0,Fiji,65.0,Trinitario,Fiji,190333.0000
1,Adi,Vanua Levu,2011,88.0,Fiji,70.0,Trinitario,Fiji,225471.4000
2,Adi,"Vanua Levu, Ami-Ami-CA",2011,72.0,Fiji,70.0,Trinitario,Fiji,184476.6000
3,Akesson's (Pralus),"Bali (west), Sukrama Family, Melaya area",2011,75.0,Switzerland,75.0,Trinitario,Indonesia,205889.0625
4,Akesson's (Pralus),"Madagascar, Ambolikapiky P.",2010,75.0,Switzerland,55.0,Criollo,Madagascar,103125.0000
...,...,...,...,...,...,...,...,...,...
790,Zotter,Raw,2014,80.0,Austria,55.0,Blend,Other,110000.0000
791,Zotter,"Bocas del Toro, Cocabo Co-op",2012,72.0,Austria,70.0,Blend,Panama,126000.0000
792,Zotter,El Oro,2012,75.0,Austria,60.0,Forastero (Nacional),Ecuador,112500.0000
793,Zotter,Huiwani Coop,2012,75.0,Austria,60.0,"Criollo, Trinitario",Papua New Guinea,112500.0000
794,Zotter,El Ceibo Coop,2012,90.0,Austria,65.0,Blend,Bolivia,146250.0000

In [18]:
priceSum = dark_chocolates['price(100g)'].sum()